name: "Raku tests"
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    container:
      image: ghcr.io/jj/raku-zef-gha
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install modules
      - run: zef install https://github.com/croservices/cro-core/archive/master.zip
      - run: zef install https://github.com/croservices/cro-tls/archive/master.zip
      - run: zef install https://github.com/croservices/cro-http/archive/master.zip
      - name: Setup dependencies
        run: raku -v && zef install --deps-only .
      - name: Test code
        run: zef --debug test .
